# Use uma imagem base Python
FROM python:3.9-slim

# Instale gcc e as ferramentas de compilação
RUN apt-get update && apt-get install -y gcc build-essential libffi-dev

# Variável para não deixar buffer no output
ENV PYTHONUNBUFFERED=1

# Define o diretório de trabalho
WORKDIR /app

# Copia o arquivo de requisitos e instala as dependências
COPY requirements.txt /app/
RUN pip install --upgrade pip && pip install -r requirements.txt

# Copia o restante do código
COPY . /app/

# Expõe a porta padrão do Django
EXPOSE 8000
