version: "3.8"
services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  django:
    build: .
    working_dir: /app/myproject
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=myproject.project_core.settings
      - CELERY_BROKER_URL=redis://redis:6379/0
    depends_on:
      - redis

  celery:
    build: .
    working_dir: /app
    command: celery -A myproject.project_core worker --loglevel=info --pool=solo
    volumes:
      - .:/app
    environment:
      - DJANGO_SETTINGS_MODULE=myproject.project_core.settings
      - CELERY_BROKER_URL=redis://redis:6379/0
    depends_on:
      - redis


  frontend:
      build:
        context: ../crm-recipe-app
        dockerfile: Dockerfile
      working_dir: /app
      ports:
        - "5173:5173"